In [9]:
import random

import numpy as np

class Graph:
    
    def minDistance(self, dist, queue):
        
        minimum = float("Inf")
        min_index = -1

        for i in range(len(dist)):
            
            if dist[i] < minimum and i in queue:
                minimum = dist[i]
                min_index = i
                
        return min_index

    def printPath(self, parent, j):
        
        if parent[j] == -1:
            print(j, end=' ', flush=True)
            return
        self.printPath(parent, parent[j]) # parent에서 그 parent로 꼬리 물어가는 재귀함수 
        print(j, end=' ', flush=True) 
        # 만약 j=2이라면 2를 프린트하고 2의 부모 노드 번호인 parent[2]를 인쇄하고 그 부모 번호를 또 인쇄하고 종료 조건까지 계속.....
        

    def printSolution(self, dist, parent, minVal, pos):
        
        src = 0
        print("\n최소 거리 노드까지의 경로 : ", end="")
        self.printPath(parent, pos)
        print("")
        
        print("\n전체 경로 살펴보기\n<Vertex>\t\t<Distance from Source>","\t"*4,"<Path>")
        
        for i in range(1, len(dist)):
            #print("\(src} --> {i} \t\t{dist} \t\t\t\t\t".format(src, i, dist[i]), end='\t', flush=True)
            #print('%d %d')
            print("\n%d --> %d \t\t%d \t\t\t\t\t" % (src, i, dist[i]), end='\t', flush=True)
            # 개행을 하지 않고 tab을 한다
            self.printPath(parent, i) # parent 리스트와 i를 받아 printpath 실행
            if (minVal == dist[i]) and (i == pos):
                print("\n","-"*100,"|", end='', flush=True)
            # distance 리스트 안에 i번째 값이 minVal 값과 같고 i가 pos = minindex(최소거리 노드 인덱스가와 같을 때 

    def dijkstra(self, graph, src, seminode):
        
        row = len(graph)
        col = len(graph[0])

        dist = [float("Inf")] * row
        # i까지의 distance를 저장할 리스트는 row의 개수만큼 저장하되 그 원소를 무한대 크기로 한다.

        parent = [-1] * row
        #-1로 초기화시켜 row 개수만큼 parent node list 생성 

        dist[src] = 0

        queue = []
        
        for i in range(row):
            
            queue.append(i)
        # 노드 숫자를 차례대로 큐에 추가 

        while queue:
            
            u = self.minDistance(dist, queue)
            # min index 송출
            
            queue.remove(u)
            #큐에서 min index를 가진 리스트 넘버 제거
            
            for i in range(col):
                
                if graph[u][i] and i in queue:
                    if dist[u] + graph[u][i] < dist[i]:
                        dist[i] = dist[u] + graph[u][i]
                        parent[i] = u
                        
        # graph[u][i]는 u와 i 사이의 노드 엣지라고 보면 된다. dist[u]는 u까지 오는데 쌓인 가중치이다. dist[i]는 i까지 갔을 때 쌓인 가중치. 당연히 i 노드의 부모는 u이다.

        target = [dist[i] for i in seminode]
        # seminode i 값에 해당하는 dist[i] 값들로 이루어져 있는 target 리스트 생성 (리스트 컴프리헨션)
        
        set = {}
        
        for i in range(len(seminode)):
            set.setdefault(seminode[i],target[i])
            
        print("Each pharmacy distance : ", set)
        # 세미노드와 타겟 리스트의 값들을 순서대로 받아로 키와 값으로 set 딕셔너리로 생성 
        
        minVal = min(target)
        # seminode 안 최솟값 구함
        minIdx = np.argmin(target)
        # 인덱스 송출 
        
        print('\nshortest distance pharmacy : ', seminode[minIdx])
        self.printSolution(dist, parent, minVal, seminode[minIdx])
        # dist 리스트, parent 리스트, minVal 값, 최소거리 노드 인덱스 받아 printsolution 실행.

        
    def random_adjacency_matrix(self, n):
        matrix = [[random.randint(0, 500) for i in range(n)] for j in range(n)]

        for i in range(n):
            matrix[i][i] = 0

        for i in range(n):
            for j in range(n):
                matrix[j][i] = matrix[i][j]

        return matrix

g = Graph()

graph = g.random_adjacency_matrix(21)
#시작점을 제외한 20개의 노드 엣지 인접행렬 생성

print("\nGraphs:")

for row in graph :
    print(row)

node = [{'node':1, 'mask':'Dental', 'quantity':3},
        {'node':2, 'mask':'KF94', 'quantity':1},
        {'node':3, 'mask':'KF80', 'quantity':2},
        {'node':4, 'mask':'Fabric', 'quantity':2},
        {'node':5, 'mask':'Dental', 'quantity':4},
        {'node':6, 'mask':'KF94', 'quantity':1},
        {'node':7, 'mask':'Denatal', 'quantity':4},
        {'node':8, 'mask':'KF80', 'quantity':4},
        {'node':9, 'mask':'Fabric', 'quantity':4},
        {'node':10, 'mask':'KF80', 'quantity':1},
        {'node':11, 'mask':'KF94', 'quantity':2},
        {'node':12, 'mask':'Dental', 'quantity':1},
        {'node':13, 'mask':'Fabric', 'quantity':1},
        {'node':14, 'mask':'KF94', 'quantity':4},
        {'node':15, 'mask':'KF80', 'quantity':2},
        {'node':16, 'mask':'Dental', 'quantity':3},
        {'node':17, 'mask':'Fabric', 'quantity':2},
        {'node':18, 'mask':'KF94', 'quantity':5},
        {'node':19, 'mask':'KF80', 'quantity':2},
        {'node':20, 'mask':'KF94', 'quantity':1}]

print("\nNodes:")
for i in node :
    print(i)

def pharmacy():
    
    mask = input("\nInput Mask Type (KF94/KF80/Dental/Fabric) :")
    quant = int(input("Input quantity (1 ~ 5) :"))
    
    seminode = []

    for i in range(0, len(node)):
        if node[i]['mask'] == mask and node[i]['quantity'] >= quant:
            Y = node[i]['node']
            seminode.append(Y)
    
    print('\ncondition satisfying pharmacy : ', seminode)

    try :
        g.dijkstra(graph, 0, seminode)


    except Exception as e:
        print(e)

pharmacy()




Graphs:
[0, 352, 266, 205, 48, 239, 139, 495, 232, 17, 389, 11, 228, 426, 23, 409, 37, 39, 294, 338, 227]
[352, 0, 363, 12, 205, 288, 384, 419, 457, 146, 286, 209, 73, 38, 350, 75, 360, 11, 83, 111, 168]
[266, 363, 0, 499, 271, 133, 87, 410, 139, 486, 277, 405, 385, 222, 359, 446, 261, 301, 338, 277, 363]
[205, 12, 499, 0, 476, 42, 391, 323, 50, 25, 314, 398, 307, 179, 185, 52, 46, 113, 353, 56, 376]
[48, 205, 271, 476, 0, 331, 467, 285, 197, 371, 334, 38, 477, 114, 200, 119, 44, 42, 417, 89, 171]
[239, 288, 133, 42, 331, 0, 415, 9, 77, 111, 263, 144, 195, 132, 372, 375, 58, 404, 151, 352, 377]
[139, 384, 87, 391, 467, 415, 0, 91, 192, 111, 66, 454, 299, 131, 107, 305, 95, 92, 231, 422, 424]
[495, 419, 410, 323, 285, 9, 91, 0, 379, 102, 34, 271, 417, 73, 187, 150, 451, 439, 152, 298, 265]
[232, 457, 139, 50, 197, 77, 192, 379, 0, 231, 442, 109, 499, 445, 336, 197, 324, 252, 35, 480, 330]
[17, 146, 486, 25, 371, 111, 111, 102, 231, 0, 384, 268, 16, 102, 398, 486, 91, 435, 334, 148, 132

개행(newline)을 원치 않을 때는 print 함수의 매개변수로 end='' 를 추가해주면 된다.

만약 이때 길이가 길어진다면 버퍼가 넘칠 수 있기 때문에 flush=True 명령을 함께 사용하는 
방법도 있다고 한다.

https://t1.daumcdn.net/cfile/tistory/998B204B5AFD0DD701

  (1) 최소값(min), 최대값(max): np.min(), np.max()

x.min(), np.min(x), min(x) 모두 동일한 결과를 반환합니다. 

In [1]: import numpy as np

In [2]: x = np.array([5, 4, 3, 2, 1, 0])

In [3]: x.min()

Out[3]: 0

In [4]: np.min(x)

Out[4]: 0

In [5]: x.max()

Out[5]: 5

In [6]: np.max(x)

Out[6]: 5

  (2) 최소값, 최대값의 색인 위치: np.argmin(), np.argmax()

In [7]: x.argmin()

Out[7]: 5

In [8]: np.argmin(x)

Out[8]: 5

In [9]: x.argmax()

Out[9]: 0

In [10]: np.argmax(x)

Out[10]: 0

  (3) 조건에 맞는 값의 색인 위치: np.where()



배열에서 3과 같거나 큰 값을 가지는 색인의 위치를 알고 싶을 때, 

In [11]: np.where(x >= 3)

Out[11]: (array([0, 1, 2], dtype=int64),)

(4) 조건에 맞는 값을 indexing 하기: x[np.where()] 



배열에서 3과 같거나 큰 값을 indexing 하고 싶을 때, 


In [12]: x[np.where(x >= 3)]

Out[12]: array([5, 4, 3])

  (5) 조건에 맞는 값을 특정 다른 값으로 변환하기

     : np.where(조건, 조건에 맞을 때 값, 조건과 다를 때 값)

배열의 값이 3과 같거나 크면 3으로 변환하고, 3보다 작으면 그대로 값을 유지하고 싶을 때, 

(for loop & if else 조건문을 사용하는 것보다 수십배 빠르므로 매우 유용함)

In [13]: np.where(x >= 3, 3, x)

Out[13]: array([3, 3, 3, 2, 1, 0])

참고로, 위의 np.where를 사용한 배열 값 변환을 for loop & if else 조건문을 사용해서 써보면 아래와 같습니다. for loop은 데이터 사이즈가 커질 경우 속도가 매우 느려지므로, 위의 대용량 데이터는 벡터화된 연산을 하는 np.where() 함수 사용을 권합니다. .

In [14]: x_2 = []

    ...: for i in list(x):

    ...: if i >= 3:

    ...: x_2.append(3)

    ...: else:

    ...: x_2.append(i)

    ...:

    ...:

In [15]: x_2 = np.asarray(x_2)
In [16]: type(x_2)
Out[16]: numpy.ndarray
In [17]: x_2
Out[17]: array([3, 3, 3, 2, 1, 0])

출처: https://rfriend.tistory.com/356 [R, Python 분석과 프로그래밍의 친구 (by R Friend)]


for 반복문을 두 번 사용하니 코드가 좀 길어졌죠? 리스트 표현식을 활용하면 코드 한 줄로 2차원 리스트를 만들 수 있습니다.

>>> a = [[0 for j in range(2)] for i in range(3)]
>>> a
[[0, 0], [0, 0], [0, 0]]
리스트 표현식 안에서 리스트 표현식을 사용했습니다. 먼저 [0 for j in range(2)]로 0을 2번 반복하여 [0, 0]으로 만들고 다시 for i in range(3)으로 [0, 0]을 3번 반복하여 [[0, 0], [0, 0], [0, 0]]으로 만듭니다.

만약 for 반복문을 한 번만 사용하고 싶다면 다음과 같이 식 부분에서 리스트 자체를 곱해주면 됩니다.

>>> a = [[0] * 2 for i in range(3)]
>>> a
[[0, 0], [0, 0], [0, 0]]
즉, 0이 1개 들어있는 리스트 [0]에 2를 곱하면 [0, 0]이 되는데, 이걸 for i in range(3)으로 3번 반복해주면 [[0, 0], [0, 0], [0, 0]]이 됩니다.


https://dojang.io/mod/page/view.php?id=2293